version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: empleadosWeb_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdempleado
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: empleadosWeb_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PASS=root